all: arq.o //pra compilar tudo precisa do arquivo.o
gcc dependencia main.c -o main

arq.o: arq.h //pro arquivo.o precisa do arquivo.h
gcc -c arq.c //e pro arquivo.h precisa do arquivo,c

clean:
rm -rf *.o

//poe make no terminal
